# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: meu-projeto-service
spec:
  selector:
    app: meu-projeto
  ports:
    - protocol: TCP
      port: 8080 # Porta que você usará para acessar
      targetPort: 80 # Porta do container definida no deployment